Revise Risk Analysis
MBRzealand/NewYorker pull request #99
Opened 2021-05-21 10:42 UTC by MBRzealand

2021-05-21 10:43 UTC, Bombohog reviewed
I dont know if i can see eye to eye on the last two, but meh.

2021-05-21 10:44 UTC, Bombohog requested changes
I approve

2021-05-21 10:45 UTC, Bombohog approved these changes
I approve now.

2021-05-24 07:52 UTC, Madictian approved these changes

2021-05-24 07:53 UTC, merged